### ISSUE TITLE
Invalid `build-system.requires` key in pyproject.toml

### ISSUE THREAD

**Issue by gothicVI** [gplepage/lsqfit#15]
Hi,

there seems to be an issue with the `numpy` requirement when trying to install into a fresh python 3.13 environment:
```bash
$ pip install corrfitter gvar lsqfit numpy
error: invalid-pyproject-build-system-requires

× Can not process lsqfit from https://files.pythonhosted.org/packages/2b/21/98a28539e2d1cbba0508ffef41d47b49c13595e93dc0b1868a5b6f615924/lsqfit-13.2.3.tar.gz
╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
    It contains an invalid requirement: "numpy>='2.0'"

note: This is an issue with the package mentioned above, not pip.
hint: See PEP 518 for the detailed specification.

No broken requirements found.
Traceback (most recent call last):
  File "/home/sebastian/git/Scripts/min_versions.py", line 95, in <module>
    globals()[pkg] = import_module(pkg)
                     ~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corrfitter'
```
then trying to do it one by one:
```bash
$ pip install lsqfit
error: invalid-pyproject-build-system-requires

× Can not process lsqfit from https://files.pythonhosted.org/packages/2b/21/98a28539e2d1cbba0508ffef41d47b49c13595e93dc0b1868a5b6f615924/lsqfit-13.2.3.tar.gz
╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
    It contains an invalid requirement: "numpy>='2.0'"

note: This is an issue with the package mentioned above, not pip.
hint: See PEP 518 for the detailed specification.

$ pip install numpy
Installing collected packages: numpy
Successfully installed numpy-2.2.1
Requirement already satisfied: numpy in ./.local/lib/python3.13/site-packages (2.2.1)

$ pip install lsqfit
error: invalid-pyproject-build-system-requires

× Can not process lsqfit from https://files.pythonhosted.org/packages/2b/21/98a28539e2d1cbba0508ffef41d47b49c13595e93dc0b1868a5b6f615924/lsqfit-13.2.3.tar.gz
╰─> This package has an invalid `build-system.requires` key in pyproject.toml.
    It contains an invalid requirement: "numpy>='2.0'"

note: This is an issue with the package mentioned above, not pip.
hint: See PEP 518 for the detailed specification.
```

Anything more I could/need to provide?

Best
Sebastian

**Comment by gothicVI** [comment]
I've just seen that this should have been fixed by https://github.com/gplepage/lsqfit/commit/d145364b44cab27396e5938f347351dedde4b796, however, the `pyproject.toml` reads as follows when downloaded from pypi or from the github releases:
```
[build-system]
requires = [ 
    "setuptools>=39.2.0", 
    "wheel",
    "numpy>='2.0'",
    "scipy>='1.13'",
    "Cython>='3.0'",
    "gvar>='13.1.1'"
    ]   
build-backend = "setuptools.build_meta"

```
manually removing the `'` solves it. So there might be an issue in packaging?

**Comment by gothicVI** [comment]
I just checked your other project and neither gvar 13.1.3, nor vegas 6.2 show the additional `'` when downloaded from the respective github releases. Hopefully this might help in debugging.

**Comment by gplepage** [comment]
Thanks for pointing out the problem. It was already fixed in the main github repository, but I seem not to have propagated the fix through to pypi, etc. Will have it repaired shortly.

**Comment by gplepage** [comment]
Should be fixed now.

Thanks again.

**Comment by gothicVI** [comment]
Can confirm that it is now solved. Thanks for the quick fix!
